### ISSUE TITLE
use `setPrimaryLogFile`

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/pymmcore-plus#108]
Core has the functions: `[s,g]etPrimaryLogFile` https://micro-manager.org/apidoc/MMCore/latest/class_c_m_m_core.html#a8d929d26376ddc5d57706730c3560d35

it looks as though they default to being empty (though possibly could be set in a config file? I know you can for channel group at least.) in which case logging is disabled.

We should set this to default to somewhere reasonable if it's empty - and then possibly also provide a function for reading from the log.

**Comment by tlambert03** [comment]
It would be easy enough to create a temporary file for this, but i wonder if there's any performance penalty such that we shouldn't necessarily enable by default?

```python
t = tempfile.NamedTemporaryFile()
core.setPrimaryLogFile(t.name)
```

In order to use that tempfile, we could either make the filename param to `setPrimaryLogFile` optional (if None, it uses the tempfile), or add a new method.  thoughts?
