### ISSUE TITLE
Should `MDARunner` manage an `io` thread for usage by anything writing to disk?

### ISSUE THREAD

**Issue by ianhi** [pymmcore-plus/pymmcore-plus#189]
I'm thinking about a more general solution to https://github.com/pymmcore-plus/napari-micromanager/pull/258

## Problem

While it's an ok solution for napari-micromanager to spawn a thread in order to update it's zarr, it's not ideal that any MDAWriter would either have to do it's work on the acquisition thread, or to go through the hassle of making it's own io thread. So as it stands there are two options:

1. Writers make their own threads
2. Writers slow down acquisitions

## Solution?

I think that this is a similar issue to what we ran into with `MDAEngine`'s having to manage timing of the next event. We can both save a lot of downstream complexity and encourage better performance on the acquisition thread by having the `MDARunner` (or a similar object) manage an single `io` thread. Downstream consumers of the results of the MDA (i.e. displays and writers) could register their `write_to_disk` functions (hopefully all GIL releasing) to be called from that thread.

```python

class MyWriter:
    def __init__(self, core, ....):
           # connect sequence started/finished signals
    def onSequenceStarted():
       ....
    def onFrame(self, idx: tuple[int,...], event, img):
         # tifffile.imsave(...)
         # zarr.something
         # other

writer = MyWriter(core)

core.mda.io.register_function(writer.onFrame)
```

and the `MDARunner` could place the event output in a cross thread queue here:
https://github.com/pymmcore-plus/pymmcore-plus/blob/5fb239ded2ae7a455dcc9e5afd6fb0ecfcb7db3e/src/pymmcore_plus/mda/_runner.py#L153

and then in the `io` thread draw from queue and do:

```python
event, img = queue.get()
idx = event_to_idx(event)

for f in self._disk_write_fxns:
    f(idx, event, img)
```

**Comment by tlambert03** [comment]
> We can both save a lot of downstream complexity and encourage better performance on the acquisition thread by having the MDARunner (or a similar object) manage an single io thread. Downstream consumers of the results of the MDA (i.e. displays and writers) could register their write_to_disk functions (hopefully all GIL releasing) to be called from that thread.

while I agree with that... I think I'm also slightly hesitant to establish a public-facing shell API until we have a better handle on what the best patterns actually look like.  In other words, the concept that MDAWriters each need to go through the hassle of making it's own io thread doesn't actually scare me too terribly at the moment, since it kinda encourages experimentation with patterns.  If we (as the primary "end-user" over at napari-micromanager) come up with a pattern that we think is the one clear way to do it, then i'd be open to upstreaming it here.  But I'm happier to experiment in our own backend implementation for quite a while before formalizing it as "the" way to do threaded io.

**Comment by tlambert03** [comment]
just realized that #262 is actually addressing this issue.  It adds an MDAThreadRelay object, which runs in another thread, receives events from the MDARunner, and relays them to anything connected
