### ISSUE TITLE
Remove terminal output when discovering available devices

### ISSUE THREAD

**Issue by felixwanitschke** [pymmcore-plus/pymmcore-plus#286]
Hello,

we are using the following code snippet to discover available devices at the startup of the programme:

````python
MMC_DEVICE_MAP = {}
core = mmc.CMMCorePlus.instance()
adapters = core.getDeviceAdapterNames()
for adapter in adapters:
    try:
        devices = []
        types = [mmc.DeviceType(type) for type in core.getAvailableDeviceTypes(adapter)]
        names = core.getAvailableDevices(adapter)
        for t in types:
            if t == mmc.DeviceType.Camera:
                devices.append(names[types.index(t)])
        if len(devices) > 0:
            MMC_DEVICE_MAP[adapter] = devices
    except:
        pass
````

When running this code we get the following output:

<img width="178" alt="image" src="https://github.com/pymmcore-plus/pymmcore-plus/assets/128509869/fafabb04-bf9c-4d34-b1ad-cb79850c794c">

Is it somehow possible to change this behaviour and remove the output?

Thanks for your help!

**Comment by tlambert03** [comment]
hey @felixwanitschke

That output there is unfortunately [hard-coded into the HIDManager.cpp](https://github.com/micro-manager/mmCoreAndDevices/blob/bd4704fe903e58570df4f8e19ed13bbba6461ce2/DeviceAdapters/HIDManager/HIDManager.cpp#L616) Device adapter file itself.  So the only thing we can do on the python side is try to swallow the stdout from the c code. 

That can be trickier than you want it to be, and it's also platform specific.  But there's a library called [wurlitzer](https://github.com/minrk/wurlitzer) that specializes in it (and some interested discussion in [this blog post](https://eli.thegreenplace.net/2015/redirecting-all-kinds-of-stdout-in-python/) if you're really curious)

pymmcore-plus does detect whether wurlitzer is available and can use it in certain cases ([see here for example](https://github.com/pymmcore-plus/pymmcore-plus/blob/main/src/pymmcore_plus/model/_device.py#L381)), and you can use it yourself:

```
pip install wurlizter
```

```python
from pymmcore_plus._util import no_stdout

with no_stdout():
    devs = core.getAvailableDevices(library_name) 
```

However, because it's still private, please let me know if that works for you and we can either make it public, or use it internally whenever core.getAvailableDevices is called.

**Comment by jacopoabramo** [comment]
Hey, @tlambert03, I'm working with @felixwanitschke on the same project. I tried your solution (sorry for the late reply) but unfortunately it doesn't work. I believe it's due to the fact that the `wurlizter` package only works natively on Linux (it's based of the `fcntl` package) while we mostly work on Windows. The replacement using `nullcontext` doesn't seem to work.

**Comment by tlambert03** [comment]
yeah, then there's probably not much we can do on our side.  `nullcontext` by the way is a no-op fallback in the case of a missing `wurlizter` import... I tried a number of things like modifying `sys.stdout` and nothing worked.

I'd say the linked issues above https://github.com/micro-manager/mmCoreAndDevices/issues/402 is the correct way to fix this... and possible the only way without some terribly invasive strategies.  since that issue exists, i'm inclined to close this as in-actionable, but let me know if you have any additional ideas

**Comment by jacopoabramo** [comment]
Yeah I'd say the issue can be closed for now, as I also don't have any idea how to fix this and it's not very critical for us at the moment. Thanks for the help nonetheless!

**Comment by tlambert03** [comment]
thanks for reporting.  I made a PR for mmCoreAndDevices here: https://github.com/micro-manager/mmCoreAndDevices/pull/413 ... will update after discussion is had over there
